# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VolumeCalculationTool
                                 A QGIS plugin
 Calculates volume based on DEM height layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-23
        copyright            : (C) 2020 by REDcatch GmbH.
        email                : support@redcatch.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VolumeCalculationTool class from file VolumeCalculationTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .volume_calculation_tool import VolumeCalculationTool
    return VolumeCalculationTool(iface)
