# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VolumeCalculationTool
                                 A QGIS plugin
 Calculates volume based on DEM height layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2020-2026 by REDcatch GmbH.
        email                : support@redcatch.at
 ***************************************************************************/

/***************************************************************************
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

 ***************************************************************************/
"""

# TODO: m3 or ft3 (cubic feet) ... depending on DEM layer projection
#       or adjustabel, like yds3 (cubic yards)

import processing
from processing.core.Processing import Processing
Processing.initialize()

from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import *
from qgis.gui import QgsMessageBar
from qgis.core import *
from qgis.analysis import QgsRasterCalculator, QgsRasterCalculatorEntry

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .volume_calculation_tool_dialog import VolumeCalculationToolDialog
from .volume_calculation_tool_dialog import BaseLevelOptions, CountOptions, DEFAULT_ATTRIBUTE_NAME, DEFAULT_ATTRIBUTE_NAME_NEG
import os.path
import shutil
import copy
import math
from datetime import datetime

MESSAGE_CATEGORY = "VolumeTask"
ACCURATE_WORKFLOW_DESCRIPTION = "ACCURATE_VOL_CALCULATION"
CONSTANT_DEFAULT_SAMPLE_MULTIPLIER = 2
DEFAULT_SAMPLE_STEP_SIZE = 1.00

ICON_PATH = ":/plugins/volume_calculation_tool/icon.svg"

NODATA_VALUE = -9999.0
GDAL_OPTIONS_LZW = "COMPRESS=LZW"
GDAL_OPTIONS_LZW_FLOAT = "COMPRESS=LZW|PREDICTOR=3"


class PolygonWrapper():
    def __init__(self, polygon_ref, identifier_string, base_line=0):
        self.polygon_ref = polygon_ref
        self.identifier_string = identifier_string
        self.base_line = base_line
    
    def copy_constructor(self):
        return PolygonWrapper(QgsGeometry(self.polygon_ref), self.identifier_string, self.base_line)
        

class VolumeTaskOptions():
    def __init__(self, polygons, sampling_height_layer, step_size_x, step_size_y, counting_option, base_line_option, base_line_height_layer, column_name, column_name_neg
                 , height_dem_band, base_dem_band, vector_layer=None, create_ndom=False):
        self.polygons = polygons
        self.height_layer = sampling_height_layer
        self.step_size_x = step_size_x
        self.step_size_y = step_size_y
        self.base_line_height_layer = base_line_height_layer
        self.counting_option = counting_option
        self.base_line_option = base_line_option
        self.vector_layer = vector_layer
        self.column_name = column_name
        self.column_name_neg = column_name_neg
        self.height_dem_band = height_dem_band
        self.base_dem_band = base_dem_band
        self.isInAccurateWorkflow = False
        self.create_ndom = bool(create_ndom)
        
    def copy_constructor(self):
        cloned_p = []
        for p in self.polygons:
            cloned_p.append(p.copy_constructor())
        if self.base_line_height_layer != None:
            return VolumeTaskOptions(cloned_p, 
                                     self.height_layer.clone(), 
                                     self.step_size_x, self.step_size_y, 
                                     self.counting_option, 
                                     self.base_line_option,
                                     self.base_line_height_layer.clone(),
                                     self.column_name,
                                     self.column_name_neg,
                                     self.height_dem_band,
                                     self.base_dem_band,
                                     self.vector_layer,
                                     self.create_ndom)
        return VolumeTaskOptions(cloned_p, 
                                 self.height_layer.clone(),
                                 self.step_size_x, self.step_size_y, 
                                 self.counting_option, 
                                 self.base_line_option,
                                 None,
                                 self.column_name,
                                 self.column_name_neg,
                                 self.height_dem_band,
                                 self.base_dem_band,
                                 self.vector_layer,
                                 self.create_ndom)
    
    def __str__(self):
        str_repr = "Polygon Layer: "+ self.vector_layer.name() + "\n"
        str_repr += "Height Layer: " + self.height_layer.name() + "\n"
        str_repr += "Base Line Option: " + str(self.base_line_option) + "\n"
        if self.isInAccurateWorkflow:
            str_repr += "Counting Option: " + str(self.counting_option) + "\n"
            str_repr += "Step Size X: " + str(self.step_size_x) + "\n"
            str_repr += "Step Size Y: " + str(self.step_size_y) + "\n"
            return str_repr
        return str_repr

class AccurateVolumeCalculationTask(QgsTask):
    
    def __init__(self, description, task_options):
        super().__init__(description, QgsTask.CanCancel)
        self.exception = None
        self.step_size_x = task_options.step_size_x
        self.step_size_y = task_options.step_size_y
        self.results = {}
        self.task_options = task_options
    
    def run(self):
        QgsMessageLog.logMessage('Started task "{}"'.format(self.description()), MESSAGE_CATEGORY, Qgis.Info)
        progress_bar_total_points = 0.0
        for poly in self.task_options.polygons:
            bounded_box = poly.polygon_ref.boundingBox()
            max_x = bounded_box.xMaximum()
            max_y = bounded_box.yMaximum()
            progress_bar_total_points += float(((bounded_box.xMaximum() - bounded_box.xMinimum()) * (bounded_box.yMaximum() - bounded_box.yMinimum()))/(self.step_size_x * self.step_size_y))
        current_progress = 0.0
        for poly in self.task_options.polygons:
            bounded_box = poly.polygon_ref.boundingBox()
            max_x = bounded_box.xMaximum()
            max_y = bounded_box.yMaximum()
            current_x = bounded_box.xMinimum() + self.step_size_x
            current_y = bounded_box.yMinimum() + self.step_size_y
            fix_x_start = current_x
            volume = 0
            neg_volume = 0
            iterations = 0
            while(current_y <= max_y):
                if self.isCanceled():
                    return False
                while(current_x <= max_x):
                    iterations += 1 
                    if poly.polygon_ref.contains(QgsPointXY(current_x, current_y)):
                        val, res = self.task_options.height_layer.dataProvider().sample(QgsPointXY(current_x, current_y), self.task_options.height_dem_band)
                        if res:
                            base_height = self.determineBaseHeight(current_x, current_y, poly, val)
                            volume, neg_volume = self.determineVolumeBasedOnOptions(volume, neg_volume, val, base_height)
                    current_x += self.step_size_x
                current_y += self.step_size_y
                current_x = fix_x_start
                current_progress += iterations
                iterations = 0
                self.setProgress(round((current_progress/progress_bar_total_points)*100, 2))
            self.results[poly.identifier_string] = (volume, neg_volume)
        return True
                
    def determineVolumeBasedOnOptions(self, current_volume, current_neg_volume, sampled_height, base_height):
        vol = current_volume
        n_vol = current_neg_volume
        absolute_height = abs(sampled_height - base_height)
        prism = (self.step_size_x * self.step_size_y * absolute_height)
        if self.task_options.counting_option == CountOptions.COUNT_ONLY_ABOVE:
            if sampled_height >= base_height:
                vol += prism
            return vol, n_vol
        if self.task_options.counting_option == CountOptions.COUNT_ONLY_BELOW:
            if sampled_height < base_height:
                vol += prism
            return vol, n_vol
        if self.task_options.counting_option == CountOptions.SUBTRACT_VOL_BELOW:
            if sampled_height >= base_height:
                vol += prism
            else:
                vol -= prism
            return vol, n_vol
        if self.task_options.counting_option == CountOptions.ADD_VOL_BELOW_TO_ABOVE:
            vol += prism
            return vol, n_vol
        if self.task_options.counting_option == CountOptions.COUNT_ABOVE_AND_BELOW:
            if sampled_height >= base_height:
                vol += prism
            else:
                n_vol += prism
            return vol, n_vol
        return vol, n_vol
    
    def determineBaseHeight(self, current_x, current_y, poly, height_layer_sample):
        if self.task_options.base_line_option == BaseLevelOptions.USE_DEM_LAYER:
            val, res = self.task_options.base_line_height_layer.dataProvider().sample(QgsPointXY(current_x, current_y), self.task_options.base_dem_band)
            if res:
                return val
            else:
                # we return the sampled height of the height layer in order to force the prism to volume 0 i.e. we skip it
                return height_layer_sample
        else:
            return poly.base_line
        
    
    def finished(self, result):
         QgsMessageLog.logMessage('Task "{name}" completed'.format(name=self.description()), MESSAGE_CATEGORY, Qgis.Success)
                                  
    
    def cancel(self):
        QgsMessageLog.logMessage('Task "{name}" was canceled'.format(name=self.description()), MESSAGE_CATEGORY, Qgis.Info) 
        super().cancel()


class VolumeCalculationTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VolumeCalculationTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Volume Calculation Tool')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        self.isInAccurateWorkflow = False
        self.create_ndom = False
        self.results = None
        self.height_layer = None
        self.vector_layer = None
        self.polygons = None
        self.identifiers = None
        self.base_line = None
        self.step_size_x = None
        self.step_size_y = None
        self.task_manager = QgsTaskManager()
        self.task_manager.allTasksFinished.connect(self.calculationFinished)
        self.task_manager.progressChanged.connect(self.updateProgressBar)
        self.current_task_options = None
        self.cancel_requested = False
        

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VolumeCalculationTool', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ICON_PATH
        self.add_action(
            icon_path,
            text=self.tr(u'Volume'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Volume Calculation Tool'),
                action)
            self.iface.removeToolBarIcon(action)


    def isRasterLayer(self, layer):
        return isinstance(layer, QgsRasterLayer)

    def isVectorLayer(self, layer):
        return isinstance(layer, QgsVectorLayer)

    def getFirstLayerByName(self, layer_name):
        matches = QgsProject.instance().mapLayersByName(layer_name)
        return matches[0] if matches else None

    def appendLogLine(self, text=""):
        self.dlg.logOutput.append(str(text))
    
    def calculationFinished(self):
        collected_results = {}
        task_was_cancelled = self.cancel_requested
        for task in self.task_manager.tasks():
            if hasattr(task, "isCanceled") and task.isCanceled():
                task_was_cancelled = True
            task_results = getattr(task, "results", None)
            if isinstance(task_results, dict) and task_results:
                collected_results.update(task_results)

        self.results = collected_results

        if task_was_cancelled:
            self.dlg.logOutput.append("Operation cancelled by user. No output was written.")
            self.dlg.progressBar.setValue(0)
            self.cancel_requested = False
            self.dlg.unlockGUI()
            return

        if not self.results:
            self.dlg.popWarningBox("No calculation results were produced. Please verify the input data, polygon coverage and processing settings.")
            self.dlg.progressBar.setValue(0)
            self.cancel_requested = False
            self.dlg.unlockGUI()
            return

        self.dlg.progressBar.setValue(60)
        self.updateOutputLog()
        self.writeResultsToLayer()
        if self.current_task_options and self.current_task_options.create_ndom:
            self.createNDOMRaster()
        else:
            self.dlg.progressBar.setValue(100)
        self.cancel_requested = False
        self.dlg.unlockGUI()

    def updateProgressBar(self, task_id, progress):
        if progress >= 0.0:
            scaled_progress = int(round(min(max(progress, 0.0), 100.0) * 0.6))
            self.dlg.progressBar.setValue(scaled_progress)
            
    def populateBandListForHeight(self, layer_name):
        self.dlg.mFieldComboBand.clear()
        try:
            band_count = QgsProject.instance().mapLayersByName(layer_name)[0].bandCount()
            band_list = []
            for i in range(1,band_count+1):
                self.dlg.mFieldComboBand.addItem(str(i))
        except IndexError:
            self.dlg.popFatalErrorBox("No DEM layers found ! Restart the plugin and make sure DEM layers are available")
            return 
        
    def populateBandListForBase(self, layer_name):
        try:
            self.dlg.mFieldComboBandBase.clear()
            band_count = QgsProject.instance().mapLayersByName(layer_name)[0].bandCount()
            band_list = []
            for i in range(1,band_count+1):
                self.dlg.mFieldComboBandBase.addItem(str(i))
        except IndexError:
            self.dlg.popFatalErrorBox("No polygon layers found ! Restart the plugin and make sure polygon layers are available")
            return
        
    def determineBandListForHeight(self, index):
        self.populateBandListForHeight(self.dlg.mFieldComboHeightLayer.currentText())
    
    def determineBandListForBase(self, index):
        self.populateBandListForBase(self.dlg.mFieldComboHeightLayerBase.currentText())
    
    def populateInputOptions(self):
        layers = QgsProject.instance().mapLayers()
        self.dlg.mFieldComboHeightLayer.clear()
        self.dlg.mFieldComboPolygon.clear()
        self.dlg.mFieldComboHeightLayerBase.clear()
        for key in layers:
            if self.isRasterLayer(layers[key]):
                self.dlg.mFieldComboHeightLayer.addItem(layers[key].name())
                self.dlg.mFieldComboHeightLayerBase.addItem(layers[key].name())
            if self.isVectorLayer(layers[key]):
                self.dlg.mFieldComboPolygon.addItem(layers[key].name())
        self.populateBandListForHeight(self.dlg.mFieldComboHeightLayer.currentText())
        self.populateBandListForBase(self.dlg.mFieldComboHeightLayerBase.currentText())
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        #if self.first_start == True:
        #    self.first_start = False
        self.dlg = VolumeCalculationToolDialog(self.updateDefaultSampleStepOnHeightLayerChange, self.determineBandListForHeight, self.determineBandListForBase, self.workflow, self.cancelLongWorkflow)
        
        self.populateInputOptions()
        self.updateDefaultSampleStepOnHeightLayerChange(0)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec() if hasattr(self.dlg, "exec") else self.dlg.exec_()
        
    def cancelLongWorkflow(self):
        self.cancel_requested = True
        self.task_manager.cancelAll()
        self.dlg.unlockGUI()
    
    def writeResultsToLayer(self):
        rounding_cutoff = self.dlg.outputAccuracy.value()
        if self.dlg.checkBox_add_field.isChecked():
            index = 0
            n_index = 0
            index = self.current_task_options.vector_layer.fields().lookupField(self.current_task_options.column_name)
            if (index == -1):
                self.current_task_options.vector_layer.dataProvider().addAttributes([QgsField(self.current_task_options.column_name, QVariant.Double)])
                self.current_task_options.vector_layer.updateFields()
            if self.current_task_options.counting_option == CountOptions.COUNT_ABOVE_AND_BELOW:
                    n_index = self.current_task_options.vector_layer.fields().lookupField(self.current_task_options.column_name_neg)
                    if (n_index == -1):
                        self.current_task_options.vector_layer.dataProvider().addAttributes([QgsField(self.current_task_options.column_name_neg, QVariant.Double)])
                        self.current_task_options.vector_layer.updateFields()
            index = self.current_task_options.vector_layer.fields().lookupField(self.current_task_options.column_name)
            if self.current_task_options.counting_option == CountOptions.COUNT_ABOVE_AND_BELOW:
                n_index = self.current_task_options.vector_layer.fields().lookupField(self.current_task_options.column_name_neg)
            with edit(self.current_task_options.vector_layer):
                missing_feature_results = 0
                for feature in self.current_task_options.vector_layer.getFeatures():
                    if feature == None:
                        continue
                    result_pair = self.results.get(feature.id()) if isinstance(self.results, dict) else None
                    if result_pair is None:
                        missing_feature_results += 1
                        continue
                    pos, neg = result_pair
                    feature.setAttribute(index, round(pos,rounding_cutoff))
                    if self.current_task_options.counting_option == CountOptions.COUNT_ABOVE_AND_BELOW:
                        feature.setAttribute(n_index, round(neg,rounding_cutoff))
                    self.current_task_options.vector_layer.updateFeature(feature)
                if missing_feature_results > 0:
                    self.dlg.popWarningBox(
                        f"{missing_feature_results} feature(s) did not receive result values. Please check feature IDs, polygon validity and whether the process was interrupted."
                    )
                    
    def workflow(self):
        try:
            self.cancel_requested = False
            self.gatherInputInfo()
            self.validateVectorConstraints()
            if not self.validateCRSConstraints():
                return
            self.current_task_options.isInAccurateWorkflow = True
            self.doAccurateWorkflow()
        except Exception as exc:
            self.dlg.unlockGUI()
            self.dlg.popFatalErrorBox(f"Unexpected processing error: {exc}")
    
    def validateMinimumInput(self):
        dem_layers = self.dlg.mFieldComboHeightLayer.count()
        vector_layers = self.dlg.mFieldComboPolygon.count()
        if vector_layers == 0 or dem_layers == 0:
            self.dlg.popFatalErrorBox("No DEM layers or polygon layers found/selected ! Closing plugin, please make sure both are available")
            self.dlg.closeIt()
        
    def validateVectorConstraints(self):
        caps = self.current_task_options.vector_layer.dataProvider().capabilities()
        if (not (caps & QgsVectorDataProvider.AddAttributes)) and self.dlg.checkBox_add_field.isChecked():
            self.dlg.popFatalErrorBox("Cannot add attributes to vector layer, change input option or check layer. Closing plugin !")
            self.dlg.closeIt()
        if (not (caps & QgsVectorDataProvider.ChangeAttributeValues)) and self.dlg.checkBox_add_field.isChecked():
            self.dlg.popFatalErrorBox("Cannot change attribute values of vector layer, change input option or check layer. Closing plugin !")
            self.dlg.closeIt()
    
    def validateCRSConstraints(self):
        crs_vector = self.current_task_options.vector_layer.crs()
        crs_height = self.current_task_options.height_layer.crs()

        vector_valid = crs_vector.isValid() if hasattr(crs_vector, "isValid") else bool(crs_vector)
        height_valid = crs_height.isValid() if hasattr(crs_height, "isValid") else bool(crs_height)

        if (not vector_valid) or (not height_valid) or crs_vector != crs_height:
            self.dlg.popWarningBox(
                "Warning - Undefined or different coordinate systems! Be sure all INPUT data have the same projection, and that the QGIS project CRS is identical or at least defined, otherwise output may be incorrect or not possible"
            )
            return True

        return True

    def gatherInputInfo(self):
        self.validateMinimumInput()
        height_layer = self.getFirstLayerByName(self.dlg.mFieldComboHeightLayer.currentText())
        vector_layer = self.getFirstLayerByName(self.dlg.mFieldComboPolygon.currentText())
        if height_layer is None or vector_layer is None:
            raise ValueError("Selected DEM or polygon layer could not be found in the current QGIS project.")
        height_base_band = int(self.dlg.mFieldComboBandBase.currentText())
        height_band = int(self.dlg.mFieldComboBand.currentText())
        polygon_list = self.wrapPolygons(vector_layer)
        counting_option = self.determineCountingOption()
        base_line_height_layer, base_line_option = self.determineBaseLineBasedOnOptions(polygon_list, height_layer)
        step_size_x = self.dlg.doubleSpinBoxSampleStepX.value()
        step_size_y = self.dlg.doubleSpinBoxSampleStepY.value()
        column_name, column_name_neg = self.getFieldName()
        self.current_task_options = VolumeTaskOptions(polygon_list, 
                                                      height_layer, 
                                                      step_size_x, step_size_y, 
                                                      counting_option, 
                                                      base_line_option, 
                                                      base_line_height_layer, 
                                                      column_name,
                                                      column_name_neg,
                                                      height_band,
                                                      height_base_band,
                                                      vector_layer,
                                                      bool(getattr(getattr(self, "dlg", None), "checkBox_create_ndom", None) and self.dlg.checkBox_create_ndom.isChecked()))
    
    def getFieldName(self):
        name_pos = self.dlg.fieldName.text()
        if name_pos == "":
            name_pos = DEFAULT_ATTRIBUTE_NAME
        name_neg = self.dlg.fieldName_2.text()
        if name_neg == "":
            name_neg = DEFAULT_ATTRIBUTE_NAME_NEG
        return name_pos, name_neg
    
    def determineCountingOption(self):
        current_option = self.dlg.mFieldComboCountingMethod.currentIndex()
        if current_option == 0:
            return CountOptions.COUNT_ABOVE_AND_BELOW
        if current_option == 1:
            return CountOptions.COUNT_ONLY_ABOVE
        if current_option == 2:
            return CountOptions.COUNT_ONLY_BELOW
        if current_option == 3:
            return CountOptions.SUBTRACT_VOL_BELOW
        if current_option == 4:
            return CountOptions.ADD_VOL_BELOW_TO_ABOVE
        return None
    
    def wrapPolygons(self, vector_layer):
        polygon_list = []
        for geom in vector_layer.getFeatures():
            polygon_list.append(PolygonWrapper(geom.geometry(), geom.id()))
        return polygon_list
    
    def determineBaseLineBasedOnOptions(self, polygon_list, height_layer):
        current_option = self.dlg.mFieldComboBaseLevelMethod.currentIndex()
        base_line_option = None
        base_line_layer = None
        if current_option == 0:
            self.getMinHeightOfPolygonVertices(polygon_list, height_layer)
            base_line_option = BaseLevelOptions.APPROXIMATE_VIA_MIN
        if current_option == 1:
            self.getAvgHeightOfPolygonVertices(polygon_list, height_layer)
            base_line_option = BaseLevelOptions.APPROXIMATE_VIA_AVG
        if current_option == 2:
            base_line_option = BaseLevelOptions.USE_DEM_LAYER
            base_line_layer = self.getFirstLayerByName(self.dlg.mFieldComboHeightLayerBase.currentText())
            if base_line_layer is None:
                raise ValueError("The selected base DEM layer could not be found in the current QGIS project.")
        if current_option == 3:
            base_line_option = BaseLevelOptions.MANUAL_BASE_LEVEL
            self.setBaseLevelManually(polygon_list)
        return base_line_layer, base_line_option

    def setBaseLevelManually(self, polygon_list):
        base_val = self.dlg.doubleSpinBoxBaseLevel.value()
        for poly in polygon_list:
            poly.base_line = base_val

    def getAvgHeightOfPolygonVertices(self, polygon_list, height_layer):
        for poly in polygon_list:
            vertices = poly.polygon_ref.vertices()
            count = 0
            average_height = 0
            for vertex in vertices:
                count += 1
                val, res = height_layer.dataProvider().sample(QgsPointXY(vertex.x(), vertex.y()), 1)
                if res:
                    average_height += val
            poly.base_line = average_height / count if count else 0
    
    def getMinHeightOfPolygonVertices(self, polygon_list, height_layer):
        for poly in polygon_list:
            vertices = poly.polygon_ref.vertices()
            min_height = 0
            have_reference_value = True
            for vertex in vertices:
                val, res = height_layer.dataProvider().sample(QgsPointXY(vertex.x(), vertex.y()), 1)
                if res:
                    if have_reference_value:
                        min_height = val
                        have_reference_value = False
                    if val < min_height:
                        min_height = val
            poly.base_line = min_height

    def getHeightLayerHorizontalUnitText(self):
        layer = self.current_task_options.height_layer
        if layer is None:
            return "unknown"
        try:
            crs = layer.crs()
            if not crs.isValid():
                return "unknown"
            unit_text = QgsUnitTypes.encodeUnit(crs.mapUnits())
            if unit_text:
                return unit_text
        except Exception:
            pass
        return "unknown"

    def getVolumeUnitLabel(self):
        unit_text = self.getHeightLayerHorizontalUnitText().lower()
        if any(token in unit_text for token in ["foot", "feet", "ft"]):
            return "ft3"
        if any(token in unit_text for token in ["meter", "metre"]):
            return "m3"
        if "yard" in unit_text:
            return "yd3"
        return "units3"

    def getOutputDirectoryForHeightLayer(self):
        if self.current_task_options is None or self.current_task_options.height_layer is None:
            return None
        source = self.current_task_options.height_layer.source()
        source_path = source.split('|')[0] if source else ''
        if source_path and os.path.exists(source_path):
            return os.path.dirname(source_path)
        project_home = QgsProject.instance().homePath()
        if project_home and os.path.isdir(project_home):
            return project_home
        return None

    def getNDOMOutputPath(self):
        output_dir = self.getOutputDirectoryForHeightLayer()
        if not output_dir:
            return None
        source = self.current_task_options.height_layer.source()
        source_path = source.split('|')[0] if source else ''
        base_name = os.path.splitext(os.path.basename(source_path))[0] if source_path else self.current_task_options.height_layer.name()
        return os.path.join(output_dir, f"{base_name}_nDOM.tif")

    def getRasterUnitLabelWithSuperscript(self):
        unit_text = self.getHeightLayerHorizontalUnitText().lower()
        if any(token in unit_text for token in ["foot", "feet", "ft"]):
            return "ft³"
        if any(token in unit_text for token in ["meter", "metre"]):
            return "m³"
        if "yard" in unit_text:
            return "yd³"
        return "units³"

    def showInfoMessage(self, title, text):
        msg_box = QMessageBox(self.dlg if hasattr(self, "dlg") else None)
        try:
            msg_box.setIcon(QMessageBox.Icon.Warning)
        except AttributeError:
            msg_box.setIcon(QMessageBox.Warning)
        msg_box.setWindowTitle(title)
        msg_box.setText(text)
        exec_fn = getattr(msg_box, "exec", None) or getattr(msg_box, "exec_", None)
        if exec_fn:
            exec_fn()

    def askWarningOkCancel(self, title, text):
        msg_box = QMessageBox(self.dlg if hasattr(self, "dlg") else None)
        try:
            msg_box.setIcon(QMessageBox.Icon.Warning)
        except AttributeError:
            msg_box.setIcon(QMessageBox.Warning)
        msg_box.setWindowTitle(title)
        msg_box.setText(text)
        try:
            ok_button = QMessageBox.StandardButton.Ok
            cancel_button = QMessageBox.StandardButton.Cancel
        except AttributeError:
            ok_button = QMessageBox.Ok
            cancel_button = QMessageBox.Cancel
        msg_box.setStandardButtons(ok_button | cancel_button)
        msg_box.setDefaultButton(ok_button)
        exec_fn = getattr(msg_box, "exec", None) or getattr(msg_box, "exec_", None)
        if not exec_fn:
            return True
        result = exec_fn()
        try:
            return result == QMessageBox.StandardButton.Ok
        except AttributeError:
            return result == QMessageBox.Ok

    def prepareNDOMOutputPath(self, output_path):
        existing_loaded = []
        normalized_output = os.path.normcase(os.path.normpath(output_path))
        for layer in list(QgsProject.instance().mapLayers().values()):
            if isinstance(layer, QgsRasterLayer):
                layer_source = getattr(layer, 'source', lambda: '')() or ''
                layer_file = layer_source.split('|')[0]
                if layer_file and os.path.normcase(os.path.normpath(layer_file)) == normalized_output:
                    existing_loaded.append(layer)

        if existing_loaded:
            warning_text = (
                'Warning - Existing _nDOM.tif output detected and currently loaded in QGIS. '
                'Press OK to close the layer and overwrite it, or Cancel to return to the plugin.'
            )
            proceed = self.askWarningOkCancel('nDOM output exists', warning_text)
            if not proceed:
                return False
            for layer in existing_loaded:
                QgsProject.instance().removeMapLayer(layer.id())

        if os.path.exists(output_path):
            try:
                os.remove(output_path)
            except OSError:
                pass
        return True

    def getPluginDirectory(self):
        return os.path.dirname(os.path.abspath(__file__))

    def getNDOMStyleTemplatePath(self):
        return os.path.join(self.getPluginDirectory(), 'ndom_default.qml')

    def buildNDOMStyleQML(self, target_qml_path, abs_max):
        template_path = self.getNDOMStyleTemplatePath()
        if abs_max <= 0.0:
            abs_max = 1.0

        step = abs_max / 4.0
        values = {
            '__CLASS_MIN__': f"{-abs_max:.1f}",
            '__CLASS_MAX__': f"{abs_max:.1f}",
            '__MIN__': f"{-abs_max:.1f}",
            '__NEG_75__': f"{-3.0 * step:.1f}",
            '__NEG_50__': f"{-2.0 * step:.1f}",
            '__NEG_25__': f"{-1.0 * step:.1f}",
            '__ZERO__': '0.0',
            '__POS_25__': f"{1.0 * step:.1f}",
            '__POS_50__': f"{2.0 * step:.1f}",
            '__POS_75__': f"{3.0 * step:.1f}",
            '__MAX__': f"{abs_max:.1f}",
        }

        with open(template_path, 'r', encoding='utf-8') as src:
            qml_text = src.read()
        for token, replacement in values.items():
            qml_text = qml_text.replace(token, replacement)
        with open(target_qml_path, 'w', encoding='utf-8') as dst:
            dst.write(qml_text)
        return target_qml_path

    def applyNDOMStyle(self, raster_layer, output_path):
        try:
            provider = raster_layer.dataProvider()
            stats = provider.bandStatistics(1, QgsRasterBandStats.All)
            min_val = float(stats.minimumValue)
            max_val = float(stats.maximumValue)
            abs_max_raw = max(abs(min_val), abs(max_val))
            if abs_max_raw <= 0.0:
                abs_max_raw = 1.0
            abs_max = math.ceil(abs_max_raw * 10.0) / 10.0
            if abs_max <= 0.0:
                abs_max = 1.0

            target_qml_path = os.path.splitext(output_path)[0] + '.qml'
            self.buildNDOMStyleQML(target_qml_path, abs_max)
            raster_layer.loadNamedStyle(target_qml_path)
            raster_layer.triggerRepaint()
            try:
                raster_layer.reload()
            except Exception:
                pass
        except Exception:
            pass

    def createBaselineRasterForNDOM(self, output_dir):
        baseline_field = "_base_lvl"
        baseline_layer = QgsVectorLayer(f"Polygon?crs={self.current_task_options.vector_layer.crs().authid()}", "ndom_baseline_polygons", "memory")
        provider = baseline_layer.dataProvider()
        provider.addAttributes([QgsField(baseline_field, QVariant.Double)])
        baseline_layer.updateFields()
        feats = []
        for poly in self.current_task_options.polygons:
            feat = QgsFeature(baseline_layer.fields())
            feat.setGeometry(poly.polygon_ref)
            feat.setAttribute(baseline_field, float(poly.base_line))
            feats.append(feat)
        provider.addFeatures(feats)
        baseline_layer.updateExtents()

        height_layer = self.current_task_options.height_layer
        pixel_x = abs(height_layer.rasterUnitsPerPixelX())
        pixel_y = abs(height_layer.rasterUnitsPerPixelY())
        baseline_raster = os.path.join(output_dir, "_tmp_ndom_baseline.tif")
        processing.run("gdal:rasterize", {
            'INPUT': baseline_layer,
            'FIELD': baseline_field,
            'BURN': 0,
            'USE_Z': False,
            'UNITS': 1,
            'WIDTH': pixel_x,
            'HEIGHT': pixel_y,
            'EXTENT': height_layer.extent(),
            'NODATA': NODATA_VALUE,
            'OPTIONS': 'COMPRESS=LZW',
            'DATA_TYPE': 6,
            'INIT': -9999,
            'INVERT': False,
            'EXTRA': '',
            'OUTPUT': baseline_raster,
        })
        return baseline_raster

    def createNDOMRaster(self):
        output_path = self.getNDOMOutputPath()
        if not output_path:
            self.dlg.progressBar.setValue(100)
            return
        if not self.prepareNDOMOutputPath(output_path):
            self.dlg.progressBar.setValue(100)
            return
        output_dir = os.path.dirname(output_path)
        os.makedirs(output_dir, exist_ok=True)
        temp_diff = os.path.join(output_dir, "_tmp_ndom_diff_float32.tif")
        temp_base = None
        try:
            height_source = self.current_task_options.height_layer.source().split('|')[0]
            calc_params = {
                'INPUT_A': height_source,
                'BAND_A': self.current_task_options.height_dem_band,
                'INPUT_C': None,
                'BAND_C': None,
                'INPUT_D': None,
                'BAND_D': None,
                'INPUT_E': None,
                'BAND_E': None,
                'INPUT_F': None,
                'BAND_F': None,
                'FORMULA': 'A-B',
                'NO_DATA': NODATA_VALUE,
                'RTYPE': 5,
                'OPTIONS': GDAL_OPTIONS_LZW_FLOAT,
                'EXTRA': '',
                'OUTPUT': temp_diff,
            }

            if self.current_task_options.base_line_option == BaseLevelOptions.USE_DEM_LAYER:
                temp_base = os.path.join(output_dir, "_tmp_ndom_base_aligned.tif")
                height_layer = self.current_task_options.height_layer
                base_layer = self.current_task_options.base_line_height_layer
                source_crs = base_layer.crs().authid() if base_layer and base_layer.crs().isValid() else None
                target_crs = height_layer.crs().authid() if height_layer and height_layer.crs().isValid() else None
                processing.run("gdal:warpreproject", {
                    'INPUT': base_layer.source().split('|')[0],
                    'SOURCE_CRS': source_crs,
                    'TARGET_CRS': target_crs,
                    'RESAMPLING': 1,
                    'NODATA': NODATA_VALUE,
                    'TARGET_RESOLUTION': abs(height_layer.rasterUnitsPerPixelX()),
                    'OPTIONS': GDAL_OPTIONS_LZW_FLOAT,
                    'DATA_TYPE': 6,
                    'TARGET_EXTENT': height_layer.extent(),
                    'TARGET_EXTENT_CRS': target_crs,
                    'MULTITHREADING': False,
                    'EXTRA': '',
                    'OUTPUT': temp_base,
                })
                calc_params['INPUT_B'] = temp_base
                calc_params['BAND_B'] = 1
            else:
                temp_base = self.createBaselineRasterForNDOM(output_dir)
                calc_params['INPUT_B'] = temp_base
                calc_params['BAND_B'] = 1

            processing.run("gdal:rastercalculator", calc_params)
            self.dlg.progressBar.setValue(75)

            height_crs = self.current_task_options.height_layer.crs() if self.current_task_options.height_layer else None
            mask_crs = self.current_task_options.vector_layer.crs() if self.current_task_options.vector_layer else None
            source_crs = height_crs if height_crs and height_crs.isValid() else None
            target_crs = mask_crs if mask_crs and mask_crs.isValid() else source_crs

            processing.run("gdal:cliprasterbymasklayer", {
                'INPUT': temp_diff,
                'MASK': self.current_task_options.vector_layer,
                'SOURCE_CRS': source_crs,
                'TARGET_CRS': target_crs,
                'NODATA': NODATA_VALUE,
                'ALPHA_BAND': False,
                'CROP_TO_CUTLINE': True,
                'KEEP_RESOLUTION': True,
                'SET_RESOLUTION': False,
                'X_RESOLUTION': None,
                'Y_RESOLUTION': None,
                'MULTITHREADING': False,
                'OPTIONS': GDAL_OPTIONS_LZW_FLOAT,
                'DATA_TYPE': 6,
                'EXTRA': '',
                'OUTPUT': output_path,
            })
            self.dlg.progressBar.setValue(90)

            ndom_layer_name = os.path.splitext(os.path.basename(output_path))[0]
            existing = QgsProject.instance().mapLayersByName(ndom_layer_name)
            normalized_output = os.path.normcase(os.path.normpath(output_path))
            for layer in existing:
                layer_source = getattr(layer, 'source', lambda: '')() or ''
                layer_file = layer_source.split('|')[0]
                if layer_file and os.path.normcase(os.path.normpath(layer_file)) == normalized_output:
                    QgsProject.instance().removeMapLayer(layer.id())
            ndom_layer = QgsRasterLayer(output_path, ndom_layer_name)
            if ndom_layer.isValid():
                self.applyNDOMStyle(ndom_layer, output_path)
                QgsProject.instance().addMapLayer(ndom_layer)
            else:
                pass
        except Exception:
            pass
        finally:
            self.dlg.progressBar.setValue(100)
            for tmp_path in [temp_diff, temp_base]:
                if tmp_path and os.path.exists(tmp_path):
                    try:
                        os.remove(tmp_path)
                    except OSError:
                        pass

    def updateOutputLog(self):
        volume_unit = self.getRasterUnitLabelWithSuperscript()
        horizontal_unit = self.getHeightLayerHorizontalUnitText()
        rounding_cutoff = self.dlg.outputAccuracy.value()

        self.appendLogLine("========== Volume Calculation ==========")
        self.appendLogLine("Time: " + datetime.now().strftime('%H:%M:%S'))
        self.appendLogLine("Polygon Layer: " + self.current_task_options.vector_layer.name())
        self.appendLogLine("Height Layer: " + self.current_task_options.height_layer.name())
        self.appendLogLine("Base Line Option: " + str(self.current_task_options.base_line_option))
        self.appendLogLine("Counting Option: " + str(self.current_task_options.counting_option))
        self.appendLogLine("Step Size X: " + str(self.current_task_options.step_size_x))
        self.appendLogLine("Step Size Y: " + str(self.current_task_options.step_size_y))

        if self.current_task_options and self.current_task_options.create_ndom:
            output_path = self.getNDOMOutputPath()
            if output_path:
                self.appendLogLine("nDOM Output: " + output_path)

        self.appendLogLine("Detected horizontal unit: " + str(horizontal_unit))
        if volume_unit == "units³":
            self.appendLogLine(
                "Volume unit could not be determined reliably from layer CRS. "
                "Results are reported in derived layer units."
            )

        self.appendLogLine("---------- Results ----------")
        for polygon_id, (above_volume, below_volume) in self.results.items():
            self.appendLogLine("Polygon Id: " + str(polygon_id))
            self.appendLogLine(f"  Above Volume ({volume_unit}): {round(above_volume, rounding_cutoff)}")
            if self.current_task_options.counting_option == CountOptions.COUNT_ABOVE_AND_BELOW:
                self.appendLogLine(f"  Below Volume ({volume_unit}): {round(below_volume, rounding_cutoff)}")

        self.appendLogLine()
        scroll_bar = self.dlg.logOutput.verticalScrollBar()
        scroll_bar.setValue(scroll_bar.maximum())

    def doAccurateWorkflow(self):
        self.dlg.progressBar.reset()
        accurate_task = AccurateVolumeCalculationTask(ACCURATE_WORKFLOW_DESCRIPTION,
                                                      self.current_task_options.copy_constructor())
        self.task_manager.addTask(accurate_task)
        self.dlg.progressBar.setValue(0)
        self.dlg.lockupGUIDuringCalculation()
        
    def updateDefaultSampleStepOnHeightLayerChange(self, index):
        step_size = self.determineDefaultSamplingFromHeightLayer()
        self.dlg.doubleSpinBoxSampleStepX.setValue(step_size)
        self.dlg.doubleSpinBoxSampleStepY.setValue(step_size)
        self.updateBaseLevelUnitLabelFromHeightLayer()

    def getSelectedHeightLayer(self):
        layer_name = self.dlg.mFieldComboHeightLayer.currentText()
        if not layer_name:
            return None
        return self.getFirstLayerByName(layer_name)

    def getUnitSuffixForLayer(self, layer):
        if layer is None:
            return "units"
        try:
            crs = layer.crs()
            if not crs.isValid():
                return "units"
            unit_text = QgsUnitTypes.encodeUnit(crs.mapUnits()).lower()
        except Exception:
            return "units"
        if any(token in unit_text for token in ["foot", "feet", "ft"]):
            return "ft"
        if any(token in unit_text for token in ["meter", "metre"]):
            return "m"
        if "yard" in unit_text:
            return "yd"
        return unit_text if unit_text else "units"

    def updateBaseLevelUnitLabelFromHeightLayer(self):
        layer = self.getSelectedHeightLayer()
        unit_suffix = self.getUnitSuffixForLayer(layer)
        if hasattr(self.dlg, "setBaseLevelUnitLabel"):
            self.dlg.setBaseLevelUnitLabel(unit_suffix)

    def determineDefaultSamplingFromHeightLayer(self):
        top_entry = self.dlg.mFieldComboHeightLayer.currentText()
        if top_entry == "":
            return DEFAULT_SAMPLE_STEP_SIZE
        x_pixel_size = round(abs(self.getFirstLayerByName(top_entry).rasterUnitsPerPixelX()),2)
        if x_pixel_size <= 0:
           return DEFAULT_SAMPLE_STEP_SIZE    
        return (x_pixel_size * CONSTANT_DEFAULT_SAMPLE_MULTIPLIER)
