# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VolumeCalculationToolDialog
                                 A QGIS plugin
 Calculates volume based on DEM height layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2020-2026 by REDcatch GmbH.
        email                : support@redcatch.at
 ***************************************************************************/

/***************************************************************************
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QDesktopServices
from qgis.PyQt.QtWidgets import QMessageBox, QFileDialog, QAbstractSpinBox
from qgis.PyQt.QtCore import QUrl, QSettings
from enum import Enum

DEFAULT_ATTRIBUTE_NAME = "V_above"
DEFAULT_ATTRIBUTE_NAME_NEG = "V_below"
ATTRIBUTE_FIELD_MAX_LENGTH = 10

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'volume_calculation_tool_dialog_base.ui'))


class BaseLevelOptions(Enum):
    APPROXIMATE_VIA_MIN = 0
    APPROXIMATE_VIA_AVG = 1
    USE_DEM_LAYER = 2
    MANUAL_BASE_LEVEL = 3
    
    def __str__(self):
        if self.value == 0:
            return "LOWEST Point: Use minimum height of polygon vertices"
        if self.value == 1:
            return "Approximate base level via AVERAGE of polygon vertices"
        if self.value == 2:
            return "Use a SECOND DEM layer as a base (Surface to Surface)"
        if self.value == 3:
            return "Manually enter base level"


class CountOptions(Enum):
    COUNT_ABOVE_AND_BELOW = 0
    COUNT_ONLY_ABOVE = 1
    COUNT_ONLY_BELOW = 2
    SUBTRACT_VOL_BELOW = 3
    ADD_VOL_BELOW_TO_ABOVE = 4
    
    def __str__(self):
        if self.value == 0:
            return "Count both, above and below (cut/fill)"
        if self.value == 1:
            return "Count only above (eg. stock pile)"
        if self.value == 2:
            return "Count only below (eg. gravel pit)"
        if self.value == 3:
            return "Subtract below count from above count"
        if self.value == 4:
            return "Add below count to above count"

        




def _exec_dialog(dialog):
    """Qt5/Qt6 compatible dialog execution helper."""
    if hasattr(dialog, "exec"):
        return dialog.exec()
    return dialog.exec_()


class VolumeCalculationToolDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, updateDefaultSampleStepOnHeightLayerChange, determineBandsForHeight, determineBandsForBase, workflow_function, cancel_long_workflow, parent=None):
        """Constructor."""
        super().__init__()
        self.setupUi(self)
        self.populateStaticOptions()
        self.toggleAccurateWorkFlow()

        self.pushButtonStartCalculation.clicked.connect(workflow_function)
        self.pushButtonCancelCalculation.clicked.connect(cancel_long_workflow)
        self.pushButtonHelp.clicked.connect(self.show_help)

        self.clearLog.clicked.connect(self.clear_log)
        self.saveLog.clicked.connect(self.log_save)

        self.mFieldComboHeightLayerBase.setEnabled(False)
        self.mFieldComboBandBase.setEnabled(False)
        self.doubleSpinBoxBaseLevel.setEnabled(False)
        
        self.mFieldComboHeightLayer.currentIndexChanged.connect(determineBandsForHeight)
        self.mFieldComboHeightLayer.currentIndexChanged.connect(updateDefaultSampleStepOnHeightLayerChange)
        self.mFieldComboHeightLayerBase.currentIndexChanged.connect(determineBandsForBase)
        self.mFieldComboBaseLevelMethod.currentIndexChanged.connect(self.onBaseLevelMethodChanged)
        
        self.progressBar.reset()
        self.progressBar.setRange(0, 100)
        self.doubleSpinBoxBaseLevel.setDecimals(3)
        no_buttons = getattr(QAbstractSpinBox, "NoButtons", None)
        if no_buttons is None and hasattr(QAbstractSpinBox, "ButtonSymbols"):
            no_buttons = getattr(QAbstractSpinBox.ButtonSymbols, "NoButtons", None)
        if no_buttons is not None:
            self.doubleSpinBoxBaseLevel.setButtonSymbols(no_buttons)
        self.doubleSpinBoxBaseLevel.setAccelerated(True)
        self.doubleSpinBoxBaseLevel.setKeyboardTracking(False)
        self.doubleSpinBoxBaseLevel.setValue(0.000)
        self.doubleSpinBoxBaseLevel.setRange(-100000, 100000)
        
        self.outputAccuracy.setValue(1)
        self.outputAccuracy.setRange(1, 10000)
        
        self.fieldName.setMaxLength(ATTRIBUTE_FIELD_MAX_LENGTH)
        self.fieldName_2.setMaxLength(ATTRIBUTE_FIELD_MAX_LENGTH)
        self.doubleSpinBoxSampleStepX.setValue(1)
        self.doubleSpinBoxSampleStepY.setValue(1)
        self.doubleSpinBoxSampleStepX.setRange(0, 100000)
        self.doubleSpinBoxSampleStepY.setRange(0, 100000)
        self.logOutput.setReadOnly(True)
        self.fieldName.setPlaceholderText(DEFAULT_ATTRIBUTE_NAME)
        self.fieldName_2.setPlaceholderText(DEFAULT_ATTRIBUTE_NAME_NEG)
        self.checkBox_add_field.setChecked(True)
        if hasattr(self, "checkBox_create_ndom"):
            remembered_ndom = QSettings().value("REDcatch/VolumeCalculationTool/create_nDOM", False, type=bool)
            self.checkBox_create_ndom.setChecked(bool(remembered_ndom))
            self.checkBox_create_ndom.toggled.connect(self.storeNDOMPreference)
        self.pushButtonExit.clicked.connect(self.closeIt)
        self.pushButtonAbout.clicked.connect(self.popAboutBox)
        self.setBaseLevelUnitLabel("m")
        self.onBaseLevelMethodChanged(self.mFieldComboBaseLevelMethod.currentIndex())
    

    def storeNDOMPreference(self, checked):
        QSettings().setValue("REDcatch/VolumeCalculationTool/create_nDOM", bool(checked))

    def setBaseLevelUnitLabel(self, unit_suffix):
        self.label_14.setText(f"Base Level ({unit_suffix})")

    def clear_log(self):
        self.logOutput.clear()

    def append_log(self, text):
        self.logOutput.append(text)

    def getBaseLevelExplanation(self, index):
        explanations = {
            BaseLevelOptions.APPROXIMATE_VIA_MIN.value: (
                "Info: *** Lowest point base level*** "
                "The base height for each polygon is derived from the minimum height the polygons vertices. "
                "Useful for simple stockpile-style at flat surfaces."
            ),
            BaseLevelOptions.APPROXIMATE_VIA_AVG.value: (
                "Info: *** Average of polygon vertices *** "
                "The base height for each polygon is approximated from the average height of the polygons vertices. "
                "Useful when the polygon edge represents a more balanced surrounding base level."
            ),
            BaseLevelOptions.USE_DEM_LAYER.value: (
                "Info: *** Second DEM layer (Surface to Surface) *** "
                "The selected base DEM is used as comparison surface. "
                "Useful for cut/fill workflows, terrain change, or comparing two surfaces directly."
            ),
            BaseLevelOptions.MANUAL_BASE_LEVEL.value: (
                "Info: *** Manual base level *** "
                "A single constant base height is used for the all polygons. "
                "Useful when you already know the reference elevation that should be used."
            ),
        }
        return explanations.get(index, "")

    def onBaseLevelMethodChanged(self, index):
        self.toggleBaseLevelOptions(index)
        self.clear_log()
        explanation = self.getBaseLevelExplanation(index)
        if explanation:
            self.append_log(explanation)

    def toggleBaseLevelOptions(self, index):
        """Enable only the controls needed for the selected base-level mode."""
        uses_second_dem = index == BaseLevelOptions.USE_DEM_LAYER.value
        uses_manual_base = index == BaseLevelOptions.MANUAL_BASE_LEVEL.value

        self.mFieldComboHeightLayerBase.setEnabled(uses_second_dem)
        self.mFieldComboBandBase.setEnabled(uses_second_dem)
        self.doubleSpinBoxBaseLevel.setEnabled(uses_manual_base)

    def closeIt(self): 
        self.close()
        
    def show_help(self):
        QDesktopServices.openUrl(QUrl('https://www.redcatch.at/qgisvolume/'))

    def toggleWorkflow(self):
        self.progressBar.reset()
        self.pushButtonStartCalculation.setEnabled(True)
        self.pushButtonCancelCalculation.setEnabled(True)

    def toggleAccurateWorkFlow(self):
        self.mFieldComboCountingMethod.setEnabled(True)
        self.doubleSpinBoxSampleStepX.setEnabled(True)
        self.doubleSpinBoxSampleStepY.setEnabled(True)
        self.mFieldComboCountingMethod.setEnabled(True)
        self.toggleWorkflow()

    def populateStaticOptions(self):
        self.mFieldComboCountingMethod.addItem(str(CountOptions.COUNT_ABOVE_AND_BELOW))
        self.mFieldComboCountingMethod.addItem(str(CountOptions.COUNT_ONLY_ABOVE))
        self.mFieldComboCountingMethod.addItem(str(CountOptions.COUNT_ONLY_BELOW))
        #self.mFieldComboCountingMethod.addItem(str(CountOptions.SUBTRACT_VOL_BELOW))
        #self.mFieldComboCountingMethod.addItem(str(CountOptions.ADD_VOL_BELOW_TO_ABOVE))
        self.mFieldComboBaseLevelMethod.addItem(str(BaseLevelOptions.APPROXIMATE_VIA_MIN))
        self.mFieldComboBaseLevelMethod.addItem(str(BaseLevelOptions.APPROXIMATE_VIA_AVG))
        self.mFieldComboBaseLevelMethod.addItem(str(BaseLevelOptions.USE_DEM_LAYER))
        self.mFieldComboBaseLevelMethod.addItem(str(BaseLevelOptions.MANUAL_BASE_LEVEL))

    
    def lockupGUIDuringCalculation(self):
        """Freeze editable controls while a calculation task is running."""
        self.mFieldComboCountingMethod.setEnabled(False)
        self.doubleSpinBoxSampleStepX.setEnabled(False)
        self.doubleSpinBoxSampleStepY.setEnabled(False)
        self.outputAccuracy.setEnabled(False)
        self.doubleSpinBoxBaseLevel.setEnabled(False)
        self.pushButtonStartCalculation.setEnabled(False)
        self.pushButtonCancelCalculation.setEnabled(True)
        self.mFieldComboHeightLayer.setEnabled(False)
        self.mFieldComboPolygon.setEnabled(False)
        self.mFieldComboBaseLevelMethod.setEnabled(False)
        self.mFieldComboHeightLayerBase.setEnabled(False)
        self.mFieldComboBandBase.setEnabled(False)
        self.checkBox_add_field.setEnabled(False)
        if hasattr(self, "checkBox_create_ndom"):
            self.checkBox_create_ndom.setEnabled(False)
        self.fieldName.setEnabled(False)
        self.fieldName_2.setEnabled(False)
        
    def unlockGUI(self):
        """Restore GUI controls after a task finished or was cancelled."""
        self.mFieldComboCountingMethod.setEnabled(True)
        self.doubleSpinBoxSampleStepX.setEnabled(True)
        self.doubleSpinBoxSampleStepY.setEnabled(True)
        self.outputAccuracy.setEnabled(True)
        self.pushButtonStartCalculation.setEnabled(True)
        self.pushButtonCancelCalculation.setEnabled(False)
        self.mFieldComboHeightLayer.setEnabled(True)
        self.mFieldComboPolygon.setEnabled(True)
        self.checkBox_add_field.setEnabled(True)
        if hasattr(self, "checkBox_create_ndom"):
            self.checkBox_create_ndom.setEnabled(True)
        self.fieldName.setEnabled(True)
        self.fieldName_2.setEnabled(True)
        self.mFieldComboBaseLevelMethod.setEnabled(True)
        self.toggleBaseLevelOptions(self.mFieldComboBaseLevelMethod.currentIndex())
        
    def popFatalErrorBox(self, error_msg):
        msgBox = QMessageBox()
        msgBox.setWindowTitle("Error")
        msgBox.setIcon(QMessageBox.Critical)
        msgBox.setText(error_msg)
        _exec_dialog(msgBox)

    def popWarningBox(self, warning_msg):
        msgBox = QMessageBox()
        msgBox.setWindowTitle("Warning")
        warning_icon = QMessageBox.Icon.Warning if hasattr(QMessageBox, "Icon") else QMessageBox.Warning
        msgBox.setIcon(warning_icon)
        msgBox.setText(warning_msg)
        _exec_dialog(msgBox)
        
    def popAboutBox(self):
        msgBox = QMessageBox()
        msgBox.setWindowTitle("About")
        msgBox.setText("Made by www.REDcatch.at team members. We also make other (hopefully) (useful) things :)")
        _exec_dialog(msgBox)
        
    def log_save(self):
        name = QFileDialog.getSaveFileName(self, 'Save Log To File')
        file = open(name[0],'w')
        log_text = self.logOutput.toPlainText()
        file.write(log_text)
        file.close()
        
    def clear_log(self):
        self.logOutput.clear()
